Adding workflow generate utils function
mayadata-io/cli-utils pull request #4
Opened 2021-01-24 16:02 UTC by rajdas98

2021-01-27 04:33 UTC, gdsoumya requested changes

2021-01-27 04:33 UTC, gdsoumya commented on pkg/chaos/workflow.go
> +}
Not all fields are considered specially metadata which might be needed in our case. ref: https://argoproj.github.io/argo/fields/#template

2021-01-27 04:33 UTC, gdsoumya commented on pkg/chaos/workflow.go
> +}
Also take a look at the other structures and try making it match with the argo spec as workflows can be using some fields that aren't here and we would have to update these structs repeatedly.

2021-01-28 06:25 UTC, gdsoumya approved these changes
lgtm

2021-01-28 06:57 UTC, arkajyotiMukherjee approved these changes
lgtm

2021-01-28 09:08 UTC, merged